name: bell
version: '1.0'
main: com.mincomk.bell.Bell
api-version: '1.20'

commands:
  init:
    description: n/a
  start:
    description: n/a
  reset:
    description: n/a
  remove:
    description: n/a